### ISSUE TITLE
Enter key does not initiate the Log in button

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#10]
At https://moduleregistry.azurewebsites.net/
Standing with cursor in the password field I must click with mouse on log in button to log in. 

Actual: When just have typed my password and hit enter on my key board, nothing happens. 

Expected: when in passowrd field with cursor and have just typed my password, hitting enter key on key board would initiate the log in button. 

Workaround: log in is initiated by clicking on log in button with mouse/cursor. 

![image](https://user-images.githubusercontent.com/57874863/111901804-67d9df00-8a3a-11eb-8868-72b39ddfb76b.png)

**Comment by danielb987** [comment]
Some links that might be helpful on this:
https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/
https://stackoverflow.com/questions/12955222/how-to-trigger-html-button-when-you-press-enter-in-textbox
https://www.w3schools.com/howto/howto_js_trigger_button_enter.asp

**Comment by fjallemark** [comment]
These links are useful when you write clients in HTML and JavaScript, which is not the case here. Everything is written in Blazor using Razor syntax with HTML and C#. The Login button is actually an anchor tag styled as a button and there is no form that is submitted. I you can find a solution that fits with the current solution, you are welcome. Take a look at the  [LoginControl](https://github.com/tellurianinteractive/Tellurian.Trains.ModulesRegistryApp/blob/master/SourceCode/App/Shared/LoginControl.razor).

**Comment by fjallemark** [comment]
This will no be considered.

**Comment by fjallemark** [comment]
Will not be considered
