### ISSUE TITLE
Editing Meeting /Tracks does not work

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#109]
Hi
I tried to edit the given "Banor" in side the meeting .
Just geting an error when trying, see attached screen shot

![image](https://user-images.githubusercontent.com/80942768/131502934-7d4e6ea3-665c-4173-8487-0e44d917ed64.png)

**Comment by fjallemark** [comment]
Hi, that's a known issue that will be corrected in the next release.

**Comment by fjallemark** [comment]
Thanks for reporting this. Fixed in release 1.3.1.
