### ISSUE TITLE
GUI design - text and dropdown not aligned. 

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#11]
A detail. 

On https://moduleregistry.azurewebsites.net/groups/4/edit the last text and field is not horisontally aligned. 

Google Chrome is up to date
Version 89.0.4389.90 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/57874863/111902491-f7cd5800-8a3d-11eb-832e-0e7267610065.png)

**Comment by fjallemark** [comment]
Fixed in 0.8.5.
