### ISSUE TITLE
Parameter lacking Unit of Measure

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#112]
This parameter is missing UOM in the description.

Is it meter or millimetres?
![image](https://user-images.githubusercontent.com/57874863/131734162-e021196f-3a82-42b3-84fd-8186b8a8cf38.png)

**Comment by AlexEhn** [comment]
I'd prefer mm actually, otherwise you will get a lot of decimals. Don't think it is easier to enter 0,73m instead on 730 mm 

The main benefit with mm is that you don't need language/county handling of the decimal point. I have noticed in a few places that the app does not accept ' , ' as decimal point but only ' . ' and that is actually a defect from a Swedish perspective.

**Comment by AlexEhn** [comment]
But I'm not sure what language I actually have configured on my profile.

How do I change language? I did not found any way to do it.

**Comment by AlexEhn** [comment]
Or you might even add two radio button m and mm and let the user decide. And add a parameter in the db for the UOM.


If you'd like to store the measurement in m in the db for other purposes, such as calculations in the traffic planning, then you add the conversation when presenting in the UI.

**Comment by fjallemark** [comment]
Actually, the field **Max transet length** is in *wagons* and neither *meter* or *millimeter*. This label will be updated with this in next release.

**Comment by AlexEhn** [comment]
That was a surprise.
How long i "a waggon" then.

Or are you actually asking for the number of wagons that the track can hold by logistical and "switch game" perspective? 
If so the length is irrelevant.
