### ISSUE TITLE
No button to previous page

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#12]
https://moduleregistry.azurewebsites.net/Modules/0/Edit/GroupOwned/4

Actual: At this page there is now function to get back to the module list for my group. 

Expected: I want an usable way to get back to https://moduleregistry.azurewebsites.net/groups/4/modules

Workaround: 

- Click in meny to get to https://moduleregistry.azurewebsites.net/Groups/Index
- Click on group module button to get to https://moduleregistry.azurewebsites.net/groups/4/modules

- Also just realised the browsers "Back" function gets me to the moudle list. 

![image](https://user-images.githubusercontent.com/57874863/111902634-b2f5f100-8a3e-11eb-9357-055fcdaf3084.png)

**Comment by fjallemark** [comment]
This will be implemented over time. Some pages already have a *back button* and all pages will have it in a near future.

**Comment by fjallemark** [comment]
Implemented in 1.0.6.
