### ISSUE TITLE
Function to import modules

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#13]
We have a separate module repository with a lot of information. 

Is there an import function/API that can be used to create modules?

**Comment by AlexEhn** [comment]
Just so  the discussion board.

**Comment by fjallemark** [comment]
Was it intentional that you closed this issue?

**Comment by AlexEhn** [comment]
Closed it as it is more of a question than an issue.

I'll try to get hold of the data. But it will be excel/csv.

**Comment by fjallemark** [comment]
Import of modules will not be a general feature that anyone can use. I will hopefully assist doing the import to save a lot of keying. So send me the files with the data, and I will take a look on it.
