### ISSUE TITLE
Add "empty return" for waybills

### ISSUE THREAD

**Issue by fjallemark** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#132]
To send a wagon or trainset in return to the origin customer is a viable case.
By adding a checkbox *empty return* in a cargo flow, it indicates to generate an additional waybill for the *empty return*  to the origin customer. These two waybills could be glued together to create a fixed turnus for wagons.

**Comment by freddepettersson** [comment]
Hi
Is it possible to sort out waybill with empty reurn bill in this case. If so is it possible to add the waybill on the pdf in the same kolum and the emptry upside down or side by side. This make i possible to easy cut and fold the two waybill together.

**Comment by fjallemark** [comment]
Implemented in release 1.7.5.
