### ISSUE TITLE
Planing of cargo flow - public or non-public 

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#133]
Idea
When setting your gargo flow to a freigthreciver we can set numbers of cars / day
My idea are to set one number Non public , this cargo waybills can only be printed by owner or meeting admin/ planer
Then we also add a new function : Public number of cars/ day.
This public waybills can be booked by a participant signed up for the meeting. This give partipipants without module a possibility to add cars in to the play in a more controlled way.
A module owner that during the play get extra cars “ black cars” sent to the module can fast become a problem of “ to many cars “ ending up on a small cargo receiver.

**Comment by fjallemark** [comment]
Thanks for the suggestion. This issue will not be considered, see previous comment.
