### ISSUE TITLE
Red labeled Cars ( rolling cars with bad performance)

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#134]
Hi
Is it possible to add a fill in checkbox and a number field on the head of cargo flow page?
when you select to generate waybill , the system generates a “ Error waybill with checkboxes”.
Epcheckboxes on Error waybill can be:

- Wrong wheel standad
- Bad coupler
- Derails
- Etc.
- Etc.
-

**Comment by fjallemark** [comment]
Implemented in 1.4.10
