### ISSUE TITLE
BUG: Invitation button /Bjud in modulägare

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#136]
Seams like the button email  invitation are linked to stations !

See picture when howering over email button

![image](https://user-images.githubusercontent.com/80942768/140616655-1f2cd7f5-7216-464f-881d-33ff3aa9e132.png)

I rried to send a new invitation to a used that already been invited , but that worked before

**Comment by fjallemark** [comment]
Fixed in release 1.4.10.
