### ISSUE TITLE
Can not veiw modules in a meeting

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#137]
I tested the new version. Alomst all funtion seams ok but It is the meeting / signup for a meeting that are not running normal.
I tried to open the meeting Grimslöv, then wanted to open MMM-2R and the button "Moduler" 
I ended up with an error! 

![image](https://user-images.githubusercontent.com/80942768/149629035-99381a2d-59cb-4126-90d8-241c9844370f.png)

**Comment by fjallemark** [comment]
Hi, from version 1.4.10 all module meeting management is temporarily disabled because the feature is reworked. It will be back soon. This button on the meeting page is now disabled.

**Comment by freddepettersson** [comment]
👍
