### ISSUE TITLE
Import/export of Cargo customer for a station

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#155]
Add a function to be able to export and import a file for easier configuration of cargo customer for a station. It could be a simple text file in csv format or similar.
This will make it easier to setup the cargo customers if you have several versions of same station.

/Benny

**Comment by fjallemark** [comment]
Importing data is inherently difficult and fragile. I have an alternative idea for making freight customer easier when you have variants of your station.

The largest variant will be the one you enter all freight customers and their cargo flow. 
The thing I will add is to add subvariants to this station, where you simply uncheck the freight customers that doesn't apply for that smaller variant.

Would that solve your problem?

**Comment by etxbct** [comment]
Yes, I guess so.
What I want to avoid is the need to create all freight customers again if a new variant is created of the station.

**Comment by fjallemark** [comment]
A better solution is to only have freight customers defined for the largest variant of the station. 
You print all waybills, but only use the relevant ones when you use a smaller variant. 
So this is more a practical thing for the station owner to select what waybills to use at each meeting.
