### ISSUE TITLE
Get error when clicking on waybills

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#157]
I have re-generated waybills and when clicking on waybills I get a white screen.
![image](https://user-images.githubusercontent.com/22001932/194511815-45d99c51-7599-4fff-a693-84639197d535.png)
When clicking reload I get
![image](https://user-images.githubusercontent.com/22001932/194511507-a3c07337-f927-448f-a33e-b0d47bee616a.png)

**Comment by fjallemark** [comment]
Is this still an issue?

**Comment by etxbct** [comment]
No it's gone now

**Comment by fjallemark** [comment]
Ok.
