### ISSUE TITLE
No information on what variant of the Station you connecting your module to

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#158]
When connecting a module to a station you have no information in the dropdown menu what variant the station are if more than one station occur with same name.

![image](https://user-images.githubusercontent.com/22001932/194538330-1ee97e4b-2895-4086-a267-ed087429d2f3.png)

**Comment by fjallemark** [comment]
Fixed in 1.7.11.
