### ISSUE TITLE
Waybills not updated after clicking "generate"

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#159]
I've changed a cargo flow from daily to just single day of delivery, but it is not changed after clicking generate.
![image](https://user-images.githubusercontent.com/22001932/194544285-f4f0ad79-80af-4efa-a513-e2c54910f95f.png)

![image](https://user-images.githubusercontent.com/22001932/194544387-df4acc70-98c3-4bc6-9c5e-f7a93d447434.png)

**Comment by fjallemark** [comment]
Fixed in 1.7.11.
