### ISSUE TITLE
Cannot delete a cargo customer

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#160]
I want to delete a cargo customer but it is still there after the delete action
![image](https://user-images.githubusercontent.com/22001932/194567265-5f2e9354-e0af-4c1c-a3f8-61515b189d74.png)

![image](https://user-images.githubusercontent.com/22001932/194566774-a0ff5bb4-8125-43dd-b19a-afb1d567c668.png)

**Comment by fjallemark** [comment]
Fixed in 1.7.11.
