### ISSUE TITLE
When assigning a module to existing station the station is changing name

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#162]
Before assigning a new module to station Bilbo FREMO variant
![image](https://user-images.githubusercontent.com/22001932/195116018-119e1089-8a01-49da-90f9-ed975c70e36e.png)
![image](https://user-images.githubusercontent.com/22001932/195116158-2003e8ca-b3c2-436e-b88d-0bfa9940d0b3.png)

After MMM-FREMO Adapter has been assigned to Bilbo FREMO variant
![image](https://user-images.githubusercontent.com/22001932/195116409-6a44235f-6570-4d7a-a68a-25d8a191c633.png)
![image](https://user-images.githubusercontent.com/22001932/195116448-560a183f-7d8d-43d4-b098-32ed65f0f491.png)

**Comment by fjallemark** [comment]
I cannot see that the station name changes. The station mane is **Bilbo** in both cases. So what changes?

**Comment by etxbct** [comment]
The name was Bilbo, FREMO, as the name of the Module plus variant. When MMM-FREMO Adapter variant Öster is included in the Station Bilbo, FREMO it change the name to Bilbo, Öster. When opening the station it is not build on Module Bilbo, FREMO, now it is build on MMM-FREMO Adapter, Öster.

**Comment by fjallemark** [comment]
Fixed in 1.7.11.
