### ISSUE TITLE
A module with a station attached cannot be deleted

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#165]
A Station cannot be deleted since delete button is missing.

A module, that is base for the station, cannot be "unhooked" from the station.
![image](https://user-images.githubusercontent.com/22001932/197708408-54e66a1c-a016-423a-82c2-e6e3693c2a53.png)

A module, that is base for the station, cannot be deleted.
![image](https://user-images.githubusercontent.com/22001932/197708337-b9ecfa86-4df2-4ba6-95a4-b330feb3c4dd.png)

**Comment by fjallemark** [comment]
Fixed in release 1.7.11.
