### ISSUE TITLE
Delete Module

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#17]
Hi
I am missing a delete button somewherw is i would like to remove or delete a module 
As creator /owner that would be great 
Always with a question "Do you really want to DELETE ?" and some buttons too accept or not ,  with default focus to NO 

![image](https://user-images.githubusercontent.com/80942768/112305911-85f44900-8c9f-11eb-9c29-e32e2d80efb5.png)

**Comment by fjallemark** [comment]
There is a delete-function, but it is disable at the moment. When you delete a module, there are a lot of consequences to consider. Should we automatically delete the station if the module is a station, or require you to delete the station first? If the module is submitted to a meeting, should you be able to delete it then? Should we analyse the consequences and let you know? 
Deleting a module is not just deleting a module, there will be cascading deletes in a number of tables, and some of the relations should block deletes and other should just cascade delete. So it is complex, and there will be NO undo-button.

**Comment by fjallemark** [comment]
The idea is that you may delete a module under the following conditions:
- The module is 100% *owned* by you.
- The module has no reference to a *station*
- The module is not submitted to any upcoming *meetings*.

**Comment by fjallemark** [comment]
Implemented in release 1.0.5.
