### ISSUE TITLE
Wrong name in way bill list view

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#170]
![image](https://user-images.githubusercontent.com/57874863/211173177-adf3c315-b441-4672-ab23-526e80e2a916.jpeg) in NJ

**Comment by AlexEhn** [comment]
Should say Grythyttan instead of Karlstad C.

**Comment by fjallemark** [comment]
Thanks for reporting. This will be corrected in release 1.8.9.
