### ISSUE TITLE
BUG FREMO no - member 

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#184]
The length of the FREMO number need to be (6 or7 digits long, version 1.9.1 are stating that numbers shall be between 1-9999

**Comment by freddepettersson** [comment]
Aha - found that the page added 046 ( countycode ) automaticly 
Sorry, but I think its more intuitively to add the complete FREMO member number

**Comment by fjallemark** [comment]
No action required.
