### ISSUE TITLE
Group owned modules - editing cargo customers

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#193]
Backround
During some editing and preparing before a meeting we found that two users can add cargo customers to a group module 
In our case Kluringared ( VMJF group). But we can not see the other users cargo customer !

So suggetion
Add a a "Editors" to the module page, creator can allow groupmebers / or singel users to Edit the module or at least the cargo part.
This editors can only look and add cargo or cargocustomers , not delete any other users data 
All cargo customers are shown to all groupmembers

**Comment by fjallemark** [comment]
The reason you cannot see each other is that it is two separate modules with the same name. One is privat owned and the other is group owned. I have now moved all customers and cargo flows to the group owned module and deleted the private owned.
