### ISSUE TITLE
Empty waybiull / wagon request

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#195]
Hi
The generated waybill for wagon request are giving goods namne instead of Empty / Leer , see prt scr below

Genererade tomvagnsbeställningar anger gods typ, se länkad print sceen.

![image](https://github.com/tellurianinteractive/Tellurian.Trains.ModulesRegistryApp/assets/80942768/55fc2e52-555d-43ba-af7d-054281799ccf)

**Comment by fjallemark** [comment]
Will be fixed in release 1.9.16.
