### ISSUE TITLE
Suggestion add to Waybill handling 

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#196]
Hi
I suggesting that a radio-box ( kryss ruta) ffor a wagon that needed or wanted to go in return to the sender  and having the same load 
Ex. "Styckegods " 

Why ; As a station owner you prepare wagons and waybills for the meeting to make sure wagons come a go to the station/ Industrial area. During the play , the wagon are used for other waybills / transports.
My suggestion are , the same as "Empty wagon waybill BUT , keeping the gods

**Comment by fjallemark** [comment]
Done.
