### ISSUE TITLE
Update 1.10.2 - BUGG ? waybill generation issues/problem in meeting page

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#198]
I have tried to generate new waybill thru the meeting page ( module )The system doesn´t generate any waybill at all.

![image](https://github.com/tellurianinteractive/Tellurian.Trains.ModulesRegistryApp/assets/80942768/f4b27001-09ce-4dba-bcf6-c529d3c27726)

**Comment by fjallemark** [comment]
This works now.
