### ISSUE TITLE
Develop - Filter function

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#200]
Hi
I have used another unit to set a filter on Users
Now when I open in a second unit several days later , the filter is still there .

Suggestion to add a button  "Remove filter" 

![Skärmbild 2024-08-12 141343](https://github.com/user-attachments/assets/13f79eeb-3470-419b-9f50-c78a4ec39e49)

**Comment by fjallemark** [comment]
Implemented in release 1.11.6.
