### ISSUE TITLE
User page - show Verktyg , and some button

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#201]
Hi
The page Users / Användare only shows "Verktyg (Tool) and select contry and a button for sending emails

See screen shop in next comment

**Comment by freddepettersson** [comment]
![Skärmbild 2024-08-21 105413](https://github.com/user-attachments/assets/4888f5fb-b9d2-4d64-aa55-296035f0a6df)

**Comment by fjallemark** [comment]
Improved in release 1.11.27.
