### ISSUE TITLE
Unclear error message - Add rolling stock

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#216]
The error message in Swedish is not clear on what the field criteria are

Seems that the limits on the field are a number between 0 och 100 m

![image](https://github.com/user-attachments/assets/d303b4fc-390e-40de-b5d5-27d8cb4fa4ee)

**Comment by fjallemark** [comment]
Fixed in release 1.11.27.
