### ISSUE TITLE
Add a station in group

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#23]
I added a module own by the group
When I wanted to add one of them as station , i got this.

Shall a magazin (like Göransberg) be a station Stefan ? 

![image](https://user-images.githubusercontent.com/80942768/112730258-dd5d1800-8f30-11eb-844e-b6a5b6998717.png)

**Comment by fjallemark** [comment]
Fixed in release 0.8.9.
