### ISSUE TITLE
No ackowledgement at password reset

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#44]
I did not remember my password and had to reset it. 

At this page I did not got any confirmation whatsoever when I hit the send button so I clicked it again becasue I did not know if it was sent. And I got two reset links on email. 

Please add some user confirmation to know that the reset link is sent. 

![image](https://user-images.githubusercontent.com/57874863/114322881-d8988680-9b22-11eb-8bbe-34055f2491b1.png)

**Comment by fjallemark** [comment]
This is by purpose to not disclose any information of existing users.
