### ISSUE TITLE
The password reset link does not work

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#45]
I got a reset link that did not seems to work. Here is the email. 
![image](https://user-images.githubusercontent.com/57874863/114322992-78561480-9b23-11eb-83f7-85f547ffba03.png)

I expected to get to a page to set a new password, but got to a page that confirmed my user instead

![image](https://user-images.githubusercontent.com/57874863/114322980-64aaae00-9b23-11eb-9da1-894cb0f0246c.png)

**Comment by fjallemark** [comment]
Fixed in version 1.0.1.
