### ISSUE TITLE
Uploading of files

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#80]
I have uploaded a pdf file and it is visible in the list of my modules.
I have also uploaded a dwg file but it is not visible in the list of my modules.

/Benny

**Comment by fjallemark** [comment]
I have tried to upload a DWG-file for Bilbo without any problems, so I can't reproduce the the error. Note that the file must have file suffix 'dwg' or 'DWG' (its case insensitive). Can you provide more information of what you are doing?

**Comment by etxbct** [comment]
I only see a pdf icon in module list so I don't know if the dwg file has been uploaded. Now it is like a black hole.
It looks like it is working but there is no way to see if the file is there.

/Benny

**Comment by fjallemark** [comment]
What are your environment?  
- Operating system
- Browser

You can also mail me the file, and I will try to upload it.

**Comment by etxbct** [comment]
Win 10
google chrome

**Comment by etxbct** [comment]
Hej,
här är filen jag provat ladda upp.

/Benny

Den tis 27 apr. 2021 kl 09:51 skrev Stefan Fjällemark <
***@***.***>:

**Comment by fjallemark** [comment]
I have successfully uploaded the file you sent me. So I have to watch what you are doing to understand what's going wrong.
