### ISSUE TITLE
Viewing Station or Modules in Group list

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#82]
This gives empty lists only if you click on any of the blue buttons.

![image](https://user-images.githubusercontent.com/22001932/116551757-86b07880-a8f8-11eb-8d3f-c2e1e059e0ba.png)

/Benny

**Comment by fjallemark** [comment]
There are no modules owned by MMM in the database.

**Comment by etxbct** [comment]
Since members can be listed I expected to get a list of all Module/Stations of the members by clicking on the blue buttons.
Any other way to get a full list of modules from other members/groups?
I have set some of my modules visible for more than just the group (domänmedlemmar). So if other set their modules visible for others outside the group, how to view them?

**Comment by fjallemark** [comment]
The group owned modules are shown at group level. The personal modules are shown for each member.
The groups you are member of does not belong to any domain, so domain visibility does not apply. For groups in the FREMO domain, any member in a FREMO group can see all other FREMO groups and their domain visible modules.
