### ISSUE TITLE
Error when edit Group modules

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#83]
Hi
I tested to open Group modules , there was a instant error , see pictures

![image](https://user-images.githubusercontent.com/80942768/116577324-a8b5f500-a910-11eb-8318-a3643c6cd857.png)

![image](https://user-images.githubusercontent.com/80942768/116577185-8ae89000-a910-11eb-9399-73074b8e28ae.png)

**Comment by fjallemark** [comment]
Sometimes something good happens when finding an error like this. So now FREMO-names will also work for group owned modules. This will be fixed in release 1.1.5.
