### ISSUE TITLE
Removing Modules from meetings

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#89]
I Reported my two modules to testträffen Värnamo.
I could cancel only one of them and get error on the other "Inte behörig".
I can report/cancel Bilbo any time.
I cannot cancel Esset after it has been reported.

![image](https://user-images.githubusercontent.com/22001932/117411250-ab69a900-af13-11eb-92db-1b299b31551c.png)

**Comment by fjallemark** [comment]
Fixed in release 1.2.3
