### ISSUE TITLE
No error indication when trying to log in with wrong password

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#9]
At site: https://moduleregistry.azurewebsites.net/
I try to log in and enter wrong password. 

Actual: when pressing log in with a non-valid password and press login, nothing happens the page stays the same

Expected: It would be good if some pop-up or notification was shown indicating that the username or passord combination was not valid.

**Comment by fjallemark** [comment]
You get a positive response when providing correct username and password - you are logged in. If not, I think its a good idea to have no response at all, because this does not reveal anything when someone is trying to log in with without correct password.
