### ISSUE TITLE
Getting error when viewing groups

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#90]
By clicking on groups I get an error on lower part of the browser to reload the page. 

![image](https://user-images.githubusercontent.com/22001932/117413640-7d399880-af16-11eb-8cb5-1f92c7374859.png)

When doing that an error page appear.

![image](https://user-images.githubusercontent.com/22001932/117413476-524f4480-af16-11eb-981a-690ff6af3052.png)

**Comment by fjallemark** [comment]
Fixed in release 1.2.3.
