### ISSUE TITLE
Delete Cargo flow

### ISSUE THREAD

**Issue by freddepettersson** [tellurianinteractive/Tellurian.Trains.ModulesRegistryApp#94]
When editing i pushed the last Delete on the page, deleting the complte customer!
Is it poosible to add a check question ?
" do you like to delete ( cargo customer) ?

May the same thing migth be needed on module

/ Fredde

**Comment by fjallemark** [comment]
Implemented in 1.2.5. Module already have a check and confirmation before deleting it.
